version: '3.3'

services:
  server:
    build: 
      context: ./
      dockerfile: ./socket_server/Dockerfile
    ports:
      - 8000:8000

  analyzer:
    build: 
      context: ./
      dockerfile: ./road_analyzer/Dockerfile

  database:
    build:
      context: ./
      dockerfile: ./database_service/Dockerfile